### ISSUE TITLE
How to tell mpv to play to specific position when it is playing?

### ISSUE THREAD

**Issue by phuongnd08** [woodruffw/ruby-mpv#5]
I'm making a video-based game using mpv gem. Wonder if there is a way to tell mpv to play from the current position to a specific position then stop? Using `session.set_property("end", position)` doesn't produce the desired effect.

**Comment by woodruffw** [comment]
Making sure I understand: you want to seek to some timestamp, play until another timestamp, and then stop?

I think you probably want an AB-loop, with a loop count of 1: https://mpv.io/manual/master/#options-ab-loop-b

**Comment by woodruffw** [comment]
Here's the corresponding IPC command: https://mpv.io/manual/master/#command-interface-ab-loop

**Comment by phuongnd08** [comment]
How can i specify the loop count?

**Comment by woodruffw** [comment]
I don't know 🙂

ruby-mpv is just a wrapper over MPV's JSON IPC -- I'm not familiar with the details of each command that MPV can take. My suggestion would be to read through the docs and, if you can't find it there, raise a question on the upstream repository.

**Comment by phuongnd08** [comment]
Okay. there isn't a simple solution with that. So I ended up using sleep to wait.
